// Copyright (c) 2015, 2025, Oracle and/or its affiliates.

//-----------------------------------------------------------------------------
//
// This software is dual-licensed to you under the Universal Permissive License
// (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
// 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
// either license.
//
// If you elect to accept the software under the Apache License, Version 2.0,
// the following applies:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-----------------------------------------------------------------------------

package com.oracle.mobile.fusabase.oracledb;

import android.app.Activity;
import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.oracle.mobile.fusabase.FusabaseException;
import com.oracle.mobile.fusabase.logger.FusabaseLogger;
import com.oracle.mobile.fusabase.utils.Utils;
import com.oracle.mobile.fusabase.task.Task;
import com.oracle.mobile.fusabase.task.TaskCompletionSource;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.Executor;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonNumber;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;
import jakarta.json.JsonString;
import jakarta.json.JsonValue;

/**
 * Represents a reference to a document in the Oracledb database.
 * Provides methods for CRUD operations (Create, Read, Update, Delete) and real-time listeners
 * on documents within collections. Supports both auto-generated and custom document IDs.
 */
public class DocumentReference extends EntityReference {

    /**
     * Logging tag for this class.
     */
    private static final String TAG = "FusabaseOradb";

    /**
     * The path segments representing the document's location.
     */
    private final List<String> path;

    /**
     * The unique identifier of the document.
     */
    private String documentId;

    /**
     * The parent document's object identifier.
     */
    private String parentOid;

    /**
     * The parent collection reference.
     */
    private final CollectionReference parent;

    /**
     * Whether the document ID has been generated by the database.
     */
    private boolean oidGenerated;

    /**
     * Manager for handling real-time listeners.
     */
    private ListenerManager<DocumentReference, DocumentSnapshot> listenerManager;

    /**
     * Temporary ID used before the actual document ID is generated.
     */
    protected final String tempId;

    protected String version;

    /**
     * Creates a reference to a document in the database.
     * Supports both auto-generated document IDs and custom document IDs.
     *
     * @param path         the path to the document in the database
     * @param parent       the parent collection reference, or null for top-level documents
     * @param oradb        the database instance
     * @param oidGenerated whether the document ID has been generated by the database
     */
    protected DocumentReference(@NonNull String path,
                                @Nullable CollectionReference parent,
                                @NonNull FusabaseOracledb oradb,
                                boolean oidGenerated) {
        super(oradb);
        this.listenerManager = new ListenerManager<>(oradb, this);
        this.path = new ArrayList<>(Arrays.asList(path.split("/")));

        this.oidGenerated = oidGenerated;

        this.tempId = oidGenerated ?
                this.path.get(this.path.size() - 1) :
                "BAAS_DOC_TEMP_ID=" + Utils.getUniqueId();

        this.documentId = this.oidGenerated ? this.path.remove(this.path.size() - 1) : tempId;

        if (this.path.isEmpty()) {
            this.parent = null;
        } else {
            this.parent = parent == null ?
                    new CollectionReference(String.join("/", this.path), null, oradb) :
                    parent;
        }

        this.path.add(documentId);
    }

    /**
     * Gets the parent collection reference of this document.
     *
     * @return the parent collection reference
     */
    @Nullable
    public CollectionReference getParent() {
        return this.parent;
    }

    /**
     * Gets the unique identifier of the document referenced by this instance.
     *
     * @return the document ID
     */
    @NonNull
    public String getId() {
        return this.documentId;
    }

    /**
     * Creates a reference to a subcollection within this document.
     *
     * @param collectionPath the path to the collection inside the document
     * @return the collection reference
     */
    @NonNull
    public CollectionReference collection(@NonNull String collectionPath) {
        Objects.requireNonNull(collectionPath, "Invalid collectionPath provided");

        if(collectionPath.isEmpty())
            throw new IllegalArgumentException("Empty collectionPath provided");

        return new CollectionReference(getPath() + "/" + collectionPath,
                this,
                getOradb());
    }

    /**
     * Checks if the document ID has not been generated yet.
     *
     * @return true if the OID is not generated, false otherwise
     */
    protected boolean isOidNotGenerated() {
        return !this.oidGenerated;
    }

    /**
     * Gets the temporary ID used before the actual document ID is generated.
     *
     * @return the temporary ID
     */
    @NonNull
    protected String getTempId() {
        return this.tempId;
    }

    @Nullable
    protected String getVersion() {
        return this.version;
    }
    /**
     * Updates the document ID after it has been generated by the database.
     * This method should be called after the OID generation.
     *
     * @param id the generated document ID
     */
    protected void updateId(@NonNull String id) {
        this.oidGenerated = true;
        this.documentId = id;
        this.path.add(id);
    }

    /**
     * Updates the path if it contains temporary IDs that need to be replaced
     * with actual generated IDs from parent documents.
     */
    protected void updatePathIfNecessary() throws FusabaseOracledbException {
        String id;
        CollectionReference colRef = this.parent;
        DocumentReference docRef;

        while (colRef.getParent() != null) {
            docRef = colRef.getParent();
            colRef = colRef.getParent().parent;
            if (this.path.contains(docRef.getTempId())) {
                if (docRef.isOidNotGenerated()) {
                    throw new FusabaseOracledbException("The parent documentReference needs to" +
                            "be generated first. The subcollection document can be set only if the " +
                            "parent is generated.", FusabaseOracledbException.Code.INVALID_ARGUMENT);
                }
                for (int i = 0; i < this.path.size(); i++) {
                    if (this.path.get(i).equals(docRef.getTempId())) {
                        this.path.set(i, docRef.getId());
                    }
                }
            }
        }
    }
    /**
     * Method to check if the provided object is same as the Document Reference
     *
     * @param o an {@code Object} that needs to be compared
     * @return boolean
     */
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof DocumentReference)) {
            return false;
        }

        DocumentReference that = (DocumentReference) o;

        return getOradb().equals(that.getOradb()) && path.equals(that.path)
                && parent.equals(that.parent) && documentId.equals(that.documentId);
    }

    /**
     * Returns a hash code value for this DocumentReference.
     * The hash code is computed based on the database instance, path, parent, and document ID.
     *
     * @return a hash code value for this DocumentReference
     */
    @Override
    public int hashCode() {
        return Objects.hash(getOradb(), path, parent, documentId);
    }

    /**
     * Method to get the path of the document Reference
     *
     * @return {@code String} Path to the document
     */
    @NonNull
    public String getPath() {
        return String.join("/", this.path);
    }

    /**
     * Method to get the path of the document as a List<String>
     *
     * @return {@code List<String>}
     */
    @NonNull
    public List<String> getPathSegments() {
        return this.path;
    }

    @NonNull
    protected JsonObject getParams(boolean snapshot) {
        JsonObjectBuilder paramsBuilder = Json.createObjectBuilder()
                .add("path", Json.createArrayBuilder(this.path));

        if(snapshot)
            paramsBuilder.add("snapshot", 1);

        return paramsBuilder.build();
    }

    /**
     * Method to fetch a document referenced by this instance with the SOURCE as DEFAULT
     *
     * @return {@code Task<DocumentSnapshot>}
     */
    @NonNull
    public Task<DocumentSnapshot> get() {
        return get(Source.DEFAULT);
    }

    @NonNull
    protected Task<DocumentReference> add(@NonNull Object data) {

        TaskCompletionSource<DocumentReference> taskCompletionSource = new TaskCompletionSource<>();
        Task<DocumentReference> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {

            try {
                updatePathIfNecessary();
                JsonObject result = this.queryHelper.setDocs(this.path,
                        data,
                        null,
                        this,
                        new TransactionOperation());
                this.version = result.get("VERSION") instanceof JsonNumber ?
                        result.get("VERSION").toString() :
                        result.getString("VERSION");
                this.documentId = result.getString("OID");
            } catch (Exception e) {
                Exception exception = e;
                if(!(exception instanceof FusabaseOracledbException))
                    exception = new FusabaseOracledbException(exception.getMessage() == null ?
                        "Internal Error Occurred" : exception.getMessage(), FusabaseOracledbException.Code.INTERNAL);
                throw new CompletionException(exception);
            }

            taskCompletionSource.setResult(this);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to fetch a document referenced by this instance with the provided SOURCE
     *
     * @param source {@code Source} The source from where the document will be fetched
     * @return {@code Task<DocumentSnapshot>}
     */
    @NonNull
    public Task<DocumentSnapshot> get(@NonNull Source source) {
        Objects.requireNonNull(source, "Invalid source provided");
        return get(source, false);
    }

    @NonNull
    @Override
    protected Task<DocumentSnapshot> get(@NonNull Source source, boolean snapshot) {
        TaskCompletionSource<DocumentSnapshot> taskCompletionSource = new TaskCompletionSource<>();
        Task<DocumentSnapshot> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            JsonObject result = null;
            try {
                updatePathIfNecessary();
                if(isOidNotGenerated())
                    throw new FusabaseOracledbException("Cannot perform get operation on the document which has " +
                        "not been generated yet.", FusabaseOracledbException.Code.INVALID_ARGUMENT);

                result = this.queryHelper.fetchDocs(this.path,
                    this.getParams(snapshot),
                    new TransactionOperation());
            } catch (Exception e) {
                Exception exception = e;
                if(!(exception instanceof FusabaseOracledbException))
                    exception = new FusabaseOracledbException(exception.getMessage() == null ?
                        "Internal Error Occurred" : exception.getMessage(), FusabaseOracledbException.Code.INTERNAL);
                throw new CompletionException(exception);
            }

            if (!result.getJsonArray("ret").isEmpty()) {
                JsonObject data = result.getJsonArray("ret").getJsonObject(0).getJsonObject("osons");
                DocumentSnapshot snap = this.getSnapFromData(data);
                this.version = snap.getVersion();
                this.documentId =snap.getId();
                taskCompletionSource.setResult(snap);
            }
            else {
                taskCompletionSource.setResult(new DocumentSnapshot(this.getOradb(),
                    null,
                    this,
                    String.join("/", this.getPathSegments()),
                    false,
                    false));
                this.version = TransactionOperation.DEFAULT_VERSION;
            }
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    @NonNull
    protected DocumentSnapshot getSnapFromData (@NonNull JsonObject document) {
        // Data can be in 2 formats
        // Document Model
        // Relational Model

        HashMap<String, Object> dataMap = DataReader.getJsonObjectDataInMap(document);
        Long index = document.getJsonNumber("INDEX") == null ? -1 : document.getJsonNumber("INDEX").longValue();
        String created = document.containsKey("CREATED") ? document.getString("CREATED") : "";
        String lastModified = document.containsKey("LAST_MODIFIED") ? document.getString("LAST_MODIFIED") : "";
        this.parentOid = document.containsKey("parent_oid") ? document.getString("parent_oid") : "";
        String version = document.containsKey("_metadata") ?
                ((HashMap<String, Object>) dataMap.get("_metadata")).get("etag").toString() :
                document.get("VERSION").getValueType() == JsonValue.ValueType.STRING
                        ? ((JsonString) document.get("VERSION")).getString()
                        : document.get("VERSION").toString();
        String asof = document.containsKey("_metadata") ?
                ((HashMap<String, Object>) dataMap.get("_metadata")).getOrDefault("asof", "").toString() : "";
        String OID = dataMap.get("OID").toString();
        String rowId = document.containsKey("rowId") ? document.getString("rowId") : document.containsKey("rid") ? document.getString("rid") : "";
        // These fields will be removed if the response is for relational
        dataMap.remove("_metadata");
        dataMap.remove("parent_oid");
        dataMap.remove("OID");

        HashMap<String, Object> documentData = dataMap.containsKey("DOCUMENT") ?
                (HashMap<String, Object>) dataMap.get("DOCUMENT") :
                dataMap;
        return new DocumentSnapshot(getOradb(),
                documentData == null ? null :
                        new Document(documentData,
                        OID,
                        created,
                        lastModified,
                        version,
                        asof,
                        index,
                        path,
                        rowId),
                this,
                String.join("/", path),
                false,
                false);
    }

    @Nullable
    protected DocumentSnapshot getSnapshotFromNotificationData(@NonNull JsonObject changedDataNotification,
                                                               @NonNull Snapshot currentSnap) throws FusabaseOracledbException {

        JsonObject document = changedDataNotification.getJsonObject("changedData");

        DocumentSnapshot currentDocSnap = (DocumentSnapshot) currentSnap;

        // Standardize the output
        JsonObjectBuilder dataBuilder = Json.createObjectBuilder(document);

        // Check if the notification for this document is stale
        if (currentDocSnap.getDocument() != null) {
            if (currentDocSnap.getDocument().getRowId().equals(changedDataNotification.getString("rowId")) ||
                    (document.containsKey("VERSION") &&
                            currentDocSnap.getDocument().getVersion().compareTo(document.getString("VERSION")) >= 0) ||
                    (document.containsKey("_metadata") && !currentDocSnap.getDocument().getAsof().isEmpty() &&
                            document.get("_metadata").asJsonObject().containsKey("asof") &&
                            currentDocSnap.getDocument().getAsof().compareTo(
                                    document.get("_metadata").asJsonObject().getString("asof")) >= 0)) {
                FusabaseLogger.e(TAG, "Unknown or stale UPDATE notification received.");
                return null;
            }
        }

        JsonArray operationsArray = changedDataNotification.getJsonArray("operations");
        String operation = operationsArray.getString(operationsArray.size()-1);

        if(operation.equals("INSERT") && currentDocSnap.getDocument() != null)
        {
            FusabaseLogger.w(TAG,
                    "Ignoring unexpected INSERT notification for reference: " + this.getPath() +
                            ", currentDocId=" + currentDocSnap.getId() +
                            ", rowId=" + changedDataNotification.getString("rowId", "") +
                            ", queryId=" + changedDataNotification.getInt("queryId", 0) +
                            ", changedDataOID=" + (document.containsKey("OID") ? document.getString("OID") : ""));
            return null;
        }

        dataBuilder.add("rowId", changedDataNotification.getString("rowId"));
        dataBuilder.add("VERSION", document.containsKey("VERSION") ?
                document.getString("VERSION") : document.containsKey("_metadata") ?
                document.get("_metadata").asJsonObject().getString("etag") : "");
        dataBuilder.add("LAST_MODIFIED", document.containsKey("LAST_MODIFIED") ? document.getString("LAST_MODIFIED") : "");
        dataBuilder.add("OID", document.containsKey("OID") ? document.getString("OID") : "");

        List<String> unwantedFields = new ArrayList<>(Arrays.asList("OID", "LAST_MODIFIED", "VERSION", "_metadata", "parent_oid"));
        JsonObject documentData = document.entrySet().stream()
                .filter(e -> !unwantedFields.contains(e.getKey()))
                .collect(Json::createObjectBuilder,
                        (b, e) -> b.add(e.getKey(), e.getValue()),
                        (b1, b2) -> {})
                .build();
        dataBuilder.add("DOCUMENT", documentData);
        return this.getSnapFromData(dataBuilder.build());
    }

    /**
     * Method to delete a document referenced by this instance
     *
     * @return {@code Task<Void>}
     */
    @NonNull
    public Task<Void> delete() {
        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                updatePathIfNecessary();
                if(isOidNotGenerated())
                    throw new FusabaseOracledbException("Cannot perform delete operation on the document which has " +
                        "not been generated yet.", FusabaseOracledbException.Code.INVALID_ARGUMENT);
                JsonObject result = this.queryHelper.removeDocs(this.path, this, new TransactionOperation());
                this.documentId = result.getString("OID");
            } catch (Exception e) {
                Exception exception = e;
                if(!(exception instanceof FusabaseOracledbException))
                    exception = new FusabaseOracledbException(exception.getMessage() == null ?
                        "Internal Error Occurred" : exception.getMessage(), FusabaseOracledbException.Code.INTERNAL);
                throw new CompletionException(exception);
            }
            taskCompletionSource.setResult(null);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to set the document in the Oradb with the provided data. Note that
     * the provided data will overwrite the existing data in the document referred
     * by this instance.
     *
     * @param data {@code Object} Data of the document
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> set(@NonNull Object data) {
        Objects.requireNonNull(data, "Invalid data provided to set()");
        return set(data, SetOptions.OVERWRITE);
    }

    /**
     * Method to set the document in the Oradb with the provided data. Note that
     * with this method you can provide options to either overwrite or merge the
     * fields of the provided data with the existing fields of the document
     * referred by this instance.
     *
     * @param data    {@code Object} Data of the document
     * @param options {@code SetOptions} SetOption
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> set(@NonNull Object data, @NonNull SetOptions options) {

        Objects.requireNonNull(data, "Invalid data provided to set()");
        Objects.requireNonNull(options, "Invalid setOptions provided to set()");

        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                updatePathIfNecessary();
                JsonObject result = this.queryHelper.setDocs(this.path,
                        data,
                        options,
                        this,
                        new TransactionOperation());
                this.version = result.get("VERSION") instanceof JsonNumber ?
                        result.get("VERSION").toString() :
                        result.getString("VERSION");
                this.documentId = result.getString("OID");
            } catch (FusabaseException e) {
                throw new CompletionException(e);
            }

            taskCompletionSource.setResult(null);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document
     *
     * @param data {@code Object} Updated data of the document
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> update(@NonNull Map<String, Object> data) {

        Objects.requireNonNull(data, "Invalid data provided to update()");

        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                updatePathIfNecessary();
                for(Map.Entry<String, Object> entry : data.entrySet())
                 {
                    if (!checkIfFieldIsCorrect(entry.getKey()))
                        throw new FusabaseOracledbException("Invalid field name  " + entry.getKey() + "provided in update.",
                            FusabaseOracledbException.Code.INVALID_ARGUMENT);
                }

                if(isOidNotGenerated())
                    throw new FusabaseOracledbException("Cannot perform update operation on the document which has " +
                        "not been generated yet.", FusabaseOracledbException.Code.INVALID_ARGUMENT);

                JsonObject result = this.queryHelper.updateDocs(this.path,
                        data,
                        this,
                        new TransactionOperation(), null);
                this.version = result.get("VERSION") instanceof JsonNumber ?
                        result.get("VERSION").toString() :
                        result.getString("VERSION");
                this.documentId = result.getString("OID");
            } catch (Exception e) {
                Exception exception = e;
                if(!(exception instanceof FusabaseOracledbException))
                    exception = new FusabaseOracledbException(exception.getMessage() == null ?
                        "Internal Error Occurred" : exception.getMessage(), FusabaseOracledbException.Code.INTERNAL);
                throw new CompletionException(exception);
            }
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    private static boolean isInvalidUpdateField(String field) {
        if (field == null || field.trim().isEmpty()) {
            return true; // Must be non-null and non-empty
        }

        // Cannot start or end with a dot
        if (field.startsWith(".") || field.endsWith(".")) {
            return true;
        }

        // Cannot contain consecutive dots
        if (field.contains("..")) {
            return true;
        }

        // Split into path segments and ensure none are empty
        String[] segments = field.split("\\.");
        for (String segment : segments) {
            if (segment.trim().isEmpty()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document. This method takes in the data in form of keys and
     * values
     *
     * @param field               {@code String} First field to update with it's name
     * @param value               {@code Object} First value of the field
     * @param moreFieldsAndValues {@code Object[]} More field value pair
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> update(@NonNull String field, @Nullable Object value,
                                      Object... moreFieldsAndValues) {

        Objects.requireNonNull(field, "Invalid field provided to update()");
        Objects.requireNonNull(value, "Invalid value provided to update()");

        Map<String, Object> data = new HashMap<>();
        data.put(field, value);

        if (moreFieldsAndValues.length % 2 != 0) {
            throw new IllegalArgumentException("Uneven number of field-value pairs.");
        }

        if(isInvalidUpdateField(field)) {
            throw new IllegalArgumentException("Invalid field name provided.");
        }

        for (int i = 0; i < moreFieldsAndValues.length; i += 2) {
            if (!(moreFieldsAndValues[i] instanceof String)) {
                throw new IllegalArgumentException("Field names must be strings.");
            }
            String key = (String) moreFieldsAndValues[i];
            Object val = moreFieldsAndValues[i + 1];
            data.put(key, val);
        }
        return update(data);
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document. This method takes in the data in form of keys and
     * values
     *
     * @param fieldPath           {@code String} First field to update with it's name
     * @param value               {@code Object} First value of the field
     * @param moreFieldsAndValues {@code Object[]} More field value pair
     * @return {@code Task<Void>}
     */
    @NonNull
    public Task<Void> update(@NonNull FieldPath fieldPath, @Nullable Object value,
                             Object... moreFieldsAndValues) {

        if(isInvalidUpdateField(fieldPath.toString())) {
            throw new IllegalArgumentException("Invalid field name provided.");
        }

        Map<String, Object> data = new HashMap<>();
        data.put(fieldPath.toString(), value);

        if (moreFieldsAndValues.length % 2 != 0) {
            throw new IllegalArgumentException("Uneven number of field-value pairs.");
        }

        for (int i = 0; i < moreFieldsAndValues.length; i += 2) {
            if (!(moreFieldsAndValues[i] instanceof FieldPath)) {
                throw new IllegalArgumentException("Field must be of type FieldPath.");
            }
            FieldPath fieldPathKey = (FieldPath) moreFieldsAndValues[i];
            if (isInvalidUpdateField(fieldPathKey.toString())) {
                throw new IllegalArgumentException("Invalid field name provided.");
            }
            Object val = moreFieldsAndValues[i + 1];
            data.put(fieldPathKey.toString(), val);
        }
        return update(data);
    }

    /**
     * Method to listen to a document referred by this document reference
     *
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull public ListenerRegistration addSnapshotListener(@NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference using an activity scoped
     * listener
     *
     * @param activity {@code Activity} Activity on whose scope this listener will be executed
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Activity activity,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(activity, "Invalid activity provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setActivity(activity)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference and executing the callback
     * onEvent on the provided executor
     *
     * @param executor {@code Executor} Executor which will be used to execute onEvent callback
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Executor executor,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(executor, "Invalid executor provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder().setExecutor(executor)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference with the provided
     * {@code MetadataChanges}
     *
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                        should trigger the onEvent callback
     * @param listener        {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(metadataChanges, "Invalid metadataChanges provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setMetadataChanges(metadataChanges).build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference with the provided
     * {@code SnapshotListenOptions}
     *
     * @param options  {@code SnapshotListenOptions} Configures snapshot listener options, specifying
     *                 whether metadata-only changes should trigger
     *                 events, the data source to listen from, the
     *                 executor for invoking the listener, or the
     *                 activity to which the listener is scoped.
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull SnapshotListenOptions options,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(options, "Invalid options provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return listenerManager.registerListener(listener, options);
    }

    /**
     * Method to listen to a document referred by this document reference using an activity scoped
     * listener along with the provided {@code MetadataChanges}
     *
     * @param activity        {@code Activity} Executor which will be used to execute onEvent callback
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                        should trigger the onEvent callback
     * @param listener        {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration object which provides a method to
     * remove the registered listener
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Activity activity,
                                                    @NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(activity, "Invalid activity provided");
        Objects.requireNonNull(metadataChanges, "Invalid metadataChanges provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setActivity(activity)
                        .setMetadataChanges(metadataChanges)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference and executing the callback
     * onEvent on the provided executor along with the provided {@code MetadataChanges}
     *
     * @param executor        {@code Executor} Executor which will be used to execute onEvent callback
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                        should trigger the onEvent callback
     * @param listener        {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Executor executor,
                                                    @NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener) {
        Objects.requireNonNull(executor, "Invalid executor provided");
        Objects.requireNonNull(metadataChanges, "Invalid metadataChanges provided");
        Objects.requireNonNull(listener, "Invalid listener provided");
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(executor)
                        .setMetadataChanges(metadataChanges)
                        .build(),
                listener);
    }

    @NonNull
    protected QueryHelper getQueryHelper() {
        return this.queryHelper;
    }

    private boolean checkIfFieldIsCorrect (@NonNull String fieldPath) {
        if (fieldPath.trim().isEmpty()) {
            return false;
        }
        // No leading/trailing dot
        if (fieldPath.startsWith(".") || fieldPath.endsWith(".")) {
            return false;
        }

        // Split into parts by dot
        String[] parts = fieldPath.split("\\.");

        for (String part : parts) {
            // No empty parts (avoids "address..city")
            if (part.isEmpty()) {
                return false;
            }

            // Invalid characters for field names
            String invalidChars = "~*/[]";
            for (char c : invalidChars.toCharArray()) {
                if (part.indexOf(c) >= 0) {
                    return false;
                }
            }
        }
        return true;
    }
}
