// Copyright (c) 2015, 2025, Oracle and/or its affiliates.

//-----------------------------------------------------------------------------
//
// This software is dual-licensed to you under the Universal Permissive License
// (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
// 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
// either license.
//
// If you elect to accept the software under the Apache License, Version 2.0,
// the following applies:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-----------------------------------------------------------------------------

package com.oracle.mobile.fusabase.oracledb;

import android.app.Activity;
import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.oracle.mobile.fusabase.logger.FusabaseLogger;
import com.oracle.mobile.fusabase.task.Task;
import com.oracle.mobile.fusabase.task.TaskCompletionSource;
import com.oracle.mobile.fusabase.FusabaseException;
import com.oracle.mobile.fusabase.utils.Utils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

/**
 * Represents a reference to a document within a duality view collection in the Oracledb database.
 * Duality views provide a unified interface for accessing both document and relational data.
 * This class provides methods for CRUD operations and real-time listeners on duality view documents.
 */
public class DualityViewDocReference extends EntityReference {

    /**
     * Logging tag for this class.
     */
    private static final String TAG = "FusabaseOradb";

    /**
     * The path segments representing the document's location.
     */
    private List<String> path;

    /**
     * The unique identifier of the document.
     */
    private String documentId;

    /**
     * The parent duality view collection reference.
     */
    private final DualityViewColReference parent;

    /**
     * Manager for handling real-time listeners.
     */
    private final ListenerManager<DualityViewDocReference, DocumentSnapshot> listenerManager;

    /**
     * Whether the document ID has been generated by the database.
     */
    private boolean oidGenerated;

    /**
     * Temporary ID used before the actual document ID is generated.
     */
    protected final String tempId;

    /**
     * Creates a reference to a duality view document in the database.
     * Supports both auto-generated document IDs and custom document IDs.
     *
     * @param path         the path to the duality view document
     * @param oradb        the database instance this document belongs to
     * @param oidGenerated whether the document ID has been generated by the database
     * @throws IllegalArgumentException if the path has more than 2 segments
     */
    protected DualityViewDocReference(@NonNull String path,
                                      @NonNull FusabaseOracledb oradb,
                                      boolean oidGenerated) {
        super(oradb);
        this.path = new ArrayList<>(Arrays.asList(path.split("/")));
        this.listenerManager = new ListenerManager<>(oradb, this);

        if (this.path.size() > 2) {
            throw new IllegalArgumentException("DualityViewDocReference cannot have path" +
                    " with more than 2 segments.");
        }

        this.oidGenerated = oidGenerated;
        this.tempId = oidGenerated ?
                this.path.get(this.path.size() - 1) :
                "BAAS_DOC_TEMP_ID=" + Utils.getUniqueId();

        this.documentId = this.oidGenerated ? this.path.remove(this.path.size() - 1) : tempId;

        if (this.path.isEmpty()) {
            this.parent = null;
        } else {
            this.parent = new DualityViewColReference(String.join("/", this.path), oradb);
        }
        this.path.add(documentId);
    }

    /**
     * Method to get the path of the duality view document reference
     * @return {@code String} Path to the document
     */
    @NonNull
    public String getPath()
    {
        return String.join("/", this.path);
    }

    @NonNull
    public List<String> getPathSegments() {return this.path;}
    /**
     * Method to get the parent of the selected duality view document
     * @return {@code DualityViewColReference } of the parent duality view collection
     */
    @NonNull
    public DualityViewColReference getParent()
    {
        return parent;
    }

    /**
     * Method to get the documentId of the document referenced by this duality view document Reference
     * @return {@code String} Id of the duality view document
     */
    @NonNull
    public String getId()
    {
        return documentId;
    }


    /**
     * Method to check if the provided object is same as the duality view document reference
     * @param o an {@code Object} that needs to be compared
     * @return boolean
     */
    public boolean equals(Object o)
    {
        if (this == o) {
            return true;
        }
        if (!(o instanceof DualityViewDocReference)) {
            return false;
        }

        DualityViewDocReference that = (DualityViewDocReference) o;

        return getOradb().equals(that.getOradb()) && path.equals(that.path)
                && parent.equals(that.parent) && documentId.equals(that.documentId);
    }

    /**
     * Returns a hash code value for this DualityViewDocReference.
     * @return int hash code value.
     */
    public int hashCode() {
        return java.util.Objects.hash(getOradb(), path, parent, documentId);
    }

    /**
     * Method to get params in JsonObject
     * @return {@code JsonObject}
     */
    @NonNull
    private JsonObject getParams(boolean snapshot) {

        JsonObjectBuilder payloadBuilder =  Json.createObjectBuilder();
        payloadBuilder.add("dv_name", this.path.get(0));

        if(path.size() > 1)
            payloadBuilder.add("oid", this.path.get(1));

        if(snapshot)
            payloadBuilder.add("snapshot", 1);

        return payloadBuilder.build();
    }

    /**
     * Method to fetch a document referenced by this instance with the SOURCE as DEFAULT
     * @return {@code Task<DocumentSnapshot>}
     */
    @NonNull
    public Task<DocumentSnapshot> get(){
        return get(Source.DEFAULT);
    }

    @NonNull
    protected Task<DualityViewDocReference> add(@NonNull Object data) {
        TaskCompletionSource<DualityViewDocReference> taskCompletionSource = new TaskCompletionSource<>();
        Task<DualityViewDocReference> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {

            try {
                JsonObject result = this.queryHelper.setDocs(this.path,
                        data,
                        null,
                        this,
                        new TransactionOperation());
            } catch (FusabaseException e) {
                throw new RuntimeException(e);
            }
            taskCompletionSource.setResult(this);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to fetch a document referenced by this instance with the provided SOURCE
     * @param source {@code Source} The source from where the document will be fetched
     * @return {@code Task<DocumentSnapshot>}
     */
    @NonNull
    public Task<DocumentSnapshot> get(@NonNull Source source){
       return get(source, false);
    }

    @NonNull
    @Override
    protected Task<DocumentSnapshot> get(@NonNull Source source, boolean snapshot) {
        TaskCompletionSource<DocumentSnapshot> taskCompletionSource = new TaskCompletionSource<>();
        Task<DocumentSnapshot> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {

            JsonObject result = null;

            try {
                result = this.queryHelper.fetchDocs(this.path,
                    this.getParams(snapshot),
                    new TransactionOperation());
            } catch (FusabaseOracledbException e) {
                throw new RuntimeException(e);
            }

            if (!result.getJsonArray("ret").isEmpty()) {
                JsonObject data = result.getJsonArray("ret").getJsonObject(0).getJsonObject("osons");
                taskCompletionSource.setResult(this.getSnapshotFromData((data)));
            }
            else {
                taskCompletionSource.setResult(new DocumentSnapshot(this.getOradb(),
                    null,
                    this,
                    String.join("/", this.getPathSegments()),
                    false,
                    false));
            }
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    @Nullable
    @Override
    protected Snapshot getSnapshotFromNotificationData(@NonNull JsonObject changedDataNotification, @NonNull Snapshot currentSnap) throws FusabaseOracledbException {
        JsonObject document = changedDataNotification.getJsonObject("changedData");

        DocumentSnapshot currentDocSnap = (DocumentSnapshot) currentSnap;

        // Standardize the output
        JsonObjectBuilder dataBuilder = Json.createObjectBuilder(document);

        // Check if the notification for this document is stale
        if (currentDocSnap.getDocument() != null) {
            if (currentDocSnap.getDocument().getRowId().equals(changedDataNotification.getString("rowId")) ||
                    (document.containsKey("VERSION") &&
                            currentDocSnap.getDocument().getVersion().compareTo(document.getString("VERSION")) >= 0)) {
                FusabaseLogger.e(TAG, "Unknown or stale UPDATE notification received.");
                return null;
            }
        }

        JsonArray operationsArray = changedDataNotification.getJsonArray("operations");
        String operation = operationsArray.getString(operationsArray.size()-1);

        if(operation.equals("INSERT") && currentDocSnap.getDocument() != null)
        {
            
            FusabaseLogger.w(TAG,
                    "Ignoring unexpected INSERT notification for duality view reference: " + this.getPath() +
                            ", currentDocId=" + currentDocSnap.getId() +
                            ", rowId=" + changedDataNotification.getString("rowId", "") +
                            ", queryId=" + changedDataNotification.getInt("queryId", 0) +
                            ", changedDataOID=" + (document.containsKey("OID") ? document.getString("OID") : ""));
            return null;
        }

        dataBuilder.add("rowId", changedDataNotification.getString("rowId"));
        dataBuilder.add("VERSION", document.containsKey("VERSION") ?
                document.getString("VERSION") : document.containsKey("_metadata") ?
                document.get("_metadata").asJsonObject().getString("etag") : "");
        dataBuilder.add("LAST_MODIFIED", document.containsKey("LAST_MODIFIED") ? document.getString("LAST_MODIFIED") : "");
        dataBuilder.add("OID", document.containsKey("OID") ? document.getString("OID") : "");

        List<String> unwantedFields = new ArrayList<>(Arrays.asList("OID", "LAST_MODIFIED", "VERSION", "_metadata", "parent_oid"));
        JsonObject documentData = document.entrySet().stream()
                .filter(e -> !unwantedFields.contains(e.getKey()))
                .collect(Json::createObjectBuilder,
                        (b, e) -> b.add(e.getKey(), e.getValue()),
                        (b1, b2) -> {})
                .build();
        dataBuilder.add("DOCUMENT", documentData);
        return this.getSnapshotFromData(dataBuilder.build());
    }

    @NonNull
    public DocumentSnapshot getSnapshotFromData(@NonNull JsonObject document) {
        HashMap<String, Object> dataMap = DataReader.getJsonObjectDataInMap(document);
        String version = ((HashMap<String, Object>) dataMap.get("_metadata"))
                .getOrDefault("etag", "").toString();
        String asof = ((HashMap<String, Object>) dataMap.get("_metadata"))
                .getOrDefault("asof", "").toString();
        return new DocumentSnapshot(getOradb(),
                new Document( dataMap,
                        (String) dataMap.getOrDefault("oid", ""),
                        (String) dataMap.getOrDefault("CREATED", ""),
                        (String) dataMap.getOrDefault("LAST_MODIFIED", ""),
                        version,
                        asof,
                        null,
                        path,
                        ""),
                this,
                String.join("/",path),
                false,
                false);
    }

    /**
     * Method to delete a document referenced by this instance
     * @return {@code Task<Void>}
     */
    @NonNull
    public Task<Void> delete(){
        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                this.queryHelper.removeDocs(this.path,
                        this,
                        new TransactionOperation());
            } catch (FusabaseException e) {
                throw new RuntimeException(e);
            }
            taskCompletionSource.setResult(null);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to set the document in the Oradb with the provided data. Note that
     * the provided data will overwrite the existing data in the document referred
     * by this instance.
     * @param data {@code Object} Data of the document
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> set(@NonNull Object data){
        return set(data, SetOptions.OVERWRITE);
    }

    /**
     * Method to set the document in the Oradb with the provided data. Note that
     * with this method you can provide options to either overwrite or merge the
     * fields of the provided data with the existing fields of the document
     * referred by this instance.
     * @param data {@code Object} Data of the document
     * @param options {@code SetOptions} SetOption
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> set(@NonNull Object data, @NonNull SetOptions options){

        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                JsonObject result = this.queryHelper.setDocs(this.path,
                        data,
                        options,
                        this,
                        new TransactionOperation());
                if(!oidGenerated)
                {
                    this.path.add(result.getString("OID"));
                    this.documentId = result.getString("OID");
                    this.oidGenerated = true;
                }

            } catch (FusabaseException e) {
                throw new RuntimeException(e);
            }
            taskCompletionSource.setResult(null);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document
     * @param data {@code Object} Updated data of the document
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> update(@NonNull Object data)
    {
        TaskCompletionSource<Void> taskCompletionSource = new TaskCompletionSource<>();
        Task<Void> task = taskCompletionSource.getTask();

        CompletableFuture<?> future = CompletableFuture.supplyAsync(() -> {
            try {
                JsonObject result = this.queryHelper.updateDocs(this.path,
                        (Map<String,Object>)data,
                        this,
                        new TransactionOperation(),
                    null);
            } catch (FusabaseException e) {
                throw new RuntimeException(e);
            }
            taskCompletionSource.setResult(null);
            return "";
        });

        taskCompletionSource.handleFuture(future);
        return task;
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document. This method takes in the data in form of keys and
     * values
     * @param field {@code String} First field to update with it's name
     * @param value {@code Object} First value of the field
     * @param moreFieldsAndValues {@code Object[]} More field value pair
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> update(@NonNull String field, @Nullable Object value,
                                      Object... moreFieldsAndValues)
    {
        Map<String, Object> data = new HashMap<>();
        data.put(field, value);

        if (moreFieldsAndValues.length % 2 != 0) {
            throw new IllegalArgumentException("Uneven number of field-value pairs.");
        }

        for (int i = 0; i < moreFieldsAndValues.length; i += 2) {
            if (!(moreFieldsAndValues[i] instanceof String)) {
                throw new IllegalArgumentException("Field names must be strings.");
            }
            String key = (String) moreFieldsAndValues[i];
            Object val = moreFieldsAndValues[i + 1];
            data.put(key, val);
        }
        return update(data);
    }

    /**
     * Method to update some fields of a document without overwriting the
     * entire document. This method takes in the data in form of keys and
     * values
     * @param fieldPath {@code String} First field to update with it's name
     * @param value {@code Object} First value of the field
     * @param moreFieldsAndValues {@code Object[]} More field value pair
     * @return {@code Task<Void>}
     */
    public @NonNull Task<Void> update(@NonNull FieldPath fieldPath, @Nullable Object value,
                                      Object... moreFieldsAndValues)
    {
        Map<String, Object> data = new HashMap<>();
        data.put(fieldPath.toString(), value);

        for (int i = 0; i < moreFieldsAndValues.length; i += 2) {
            if (!(moreFieldsAndValues[i] instanceof FieldPath)) {
                throw new IllegalArgumentException("Field must be of type FieldPath.");
            }
            String key = (String) moreFieldsAndValues[i];
            Object val = moreFieldsAndValues[i + 1];
            data.put(key, val);
        }
        return update(data);
    }

    /**
     * Method to listen to a document referred by this document reference
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    public ListenerRegistration addSnapshotListener(@NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference using an activity scoped
     * listener
     * @param activity {@code Activity} Activity on whose scope this listener will be executed
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener( @NonNull Activity activity,
                                                     @NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setActivity(activity)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference and executing the callback
     * onEvent on the provided executor
     * @param executor {@code Executor} Executor which will be used to execute onEvent callback
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Executor executor,
                                                    @NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener(new SnapshotListenOptions.Builder().setExecutor(executor)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference with the provided
     * {@code MetadataChanges}
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                                                should trigger the onEvent callback
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener( new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setMetadataChanges(metadataChanges).build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference with the provided
     * {@code SnapshotListenOptions}
     * @param options {@code SnapshotListenOptions} Configures snapshot listener options, specifying
     *                                            whether metadata-only changes should trigger
     *                                             events, the data source to listen from, the
     *                                             executor for invoking the listener, or the
     *                                             activity to which the listener is scoped.
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull SnapshotListenOptions options,
                                                    @NonNull EventListener<DocumentSnapshot> listener)
    {
        return listenerManager.registerListener(listener, options);
    }

    /**
     * Method to listen to a document referred by this document reference using an activity scoped
     * listener along with the provided {@code MetadataChanges}
     * @param activity {@code Activity} Executor which will be used to execute onEvent callback
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                                                should trigger the onEvent callback
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration object which provides a method to
     * remove the registered listener
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Activity activity,
                                                    @NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(command -> new Handler(Looper.getMainLooper()).post(command))
                        .setActivity(activity)
                        .setMetadataChanges(metadataChanges)
                        .build(),
                listener);
    }

    /**
     * Method to listen to a document referred by this document reference and executing the callback
     * onEvent on the provided executor along with the provided {@code MetadataChanges}
     * @param executor {@code Executor} Executor which will be used to execute onEvent callback
     * @param metadataChanges {@code MetadataChanges} Indicator used to specify whether metadata changes
     *                                               should trigger the onEvent callback
     * @param listener {@code EventListener<DocumentSnapshot>} Snapshot listener
     * @return {@code ListenerRegistration} Listener Registration
     */
    @NonNull
    public ListenerRegistration addSnapshotListener(@NonNull Executor executor,
                                                    @NonNull MetadataChanges metadataChanges,
                                                    @NonNull EventListener<DocumentSnapshot> listener)
    {
        return addSnapshotListener(new SnapshotListenOptions.Builder()
                        .setExecutor(executor)
                        .setMetadataChanges(metadataChanges)
                        .build(),
                listener);
    }

    protected boolean isOidNotGenerated() {
        return !this.oidGenerated;
    }

    @NonNull
    protected String getTempId() {
        return this.tempId;
    }

    // Should be called after the generation of OID
    protected void updateId (@NonNull String id){
        this.oidGenerated = true;
        this.documentId = id;
        this.path.add(id);
        }

    @Override
    protected void updatePathIfNecessary() {
        String id;
        DualityViewColReference colRef = this.parent;
        DualityViewDocReference docRef;
    }
}
