// Copyright (c) 2015, 2025, Oracle and/or its affiliates.

//-----------------------------------------------------------------------------
//
// This software is dual-licensed to you under the Universal Permissive License
// (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
// 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
// either license.
//
// If you elect to accept the software under the Apache License, Version 2.0,
// the following applies:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-----------------------------------------------------------------------------

package com.oracle.mobile.fusabase.oracledb;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.oracle.mobile.fusabase.task.Task;

/**
 * Represents a reference to a duality view collection in the Oracledb database.
 * Duality views provide a unified interface for accessing both document and relational data.
 * This class provides methods for creating document references and performing collection operations
 * within duality view contexts.
 */
public class DualityViewColReference extends Query {

    /**
     * The type of this collection (always DUALITY_VIEW_COLLECTION).
     */
    private final Query.CollectionType type;

    /**
     * The parent document reference (always null for duality view collections).
     */
    private final DualityViewDocReference parent;

    /**
     * The unique identifier of this duality view collection.
     */
    private final String collectionId;
    /**
     * Creates a reference to a duality view collection in the database.
     * Duality view collections are top-level collections that don't have parent documents.
     *
     * @param path  the path to the duality view collection
     * @param oradb the database instance this collection belongs to
     * @throws IllegalArgumentException if the path contains parent segments (duality views are top-level)
     */
    protected DualityViewColReference(@NonNull String path, @NonNull FusabaseOracledb oradb) {
        super(oradb, path, true, false);

        this.type = CollectionType.DUALITY_VIEW_COLLECTION;

        this.collectionId = this.path.remove(this.path.size() - 1);

        this.parent = null;

        if (!this.path.isEmpty()) {
            throw new IllegalArgumentException("DualityViewColReference will have its parents as null.");
        }

        this.path.add(collectionId);
    }

    /**
     * Creates a new document in the duality view collection with an auto-generated ID.
     * The document ID will be generated by the database when the document is saved.
     *
     * @return a reference to the new document
     */
    public @NonNull DualityViewDocReference document() {
        return new DualityViewDocReference(String.join("/", path), oradb, false);
    }

    /**
     * Creates a reference to an existing document in the duality view collection.
     * Use this method when you know the document ID.
     *
     * @param documentPath the path to the document within this collection
     * @return a reference to the specified document
     */
    public @NonNull DualityViewDocReference document(@NonNull String documentPath) {
        return new DualityViewDocReference(String.join("/", this.path) + "/" + documentPath, oradb, true);
    }

    /**
     * Adds a document to the duality view collection with auto-generated ID.
     * This is a convenience method that creates a document reference and adds the data.
     *
     * @param data the document data to add
     * @return a task that resolves to the document reference once the document is added
     */
    public @NonNull Task<DualityViewDocReference> add(@NonNull Object data) {
        return this.document().add(data);
    }

    /**
     * Gets the unique identifier of this duality view collection.
     *
     * @return the collection ID
     */
    public @NonNull String getId() {
        return collectionId;
    }

    /**
     * Gets the full path to this duality view collection in the database.
     *
     * @return the collection path
     */
    public @NonNull String getPath() {
        return String.join("/", this.path);
    }

    /**
     * Gets the parent document reference of this collection.
     * For duality view collections, this always returns null since they are top-level collections.
     *
     * @return always null for duality view collections
     */
    @Nullable
    public DualityViewDocReference getParent() {
        return null;
    }

}
